### PR TITLE
Don't depend on external git

### PR DESCRIPTION
**Pull request by leg0**
Using libgit2 instead of depending on git being installed. This makes the code a bit simpler, and it feels a bit faster than starting git externally.

### CODE REVIEW

**Comment by smithx** [comment]
Thank you! 
I try to build it
```
1>LINK : fatal error LNK1181: cannot open input file 'git2.lib'
1>Done building project "GitBranch.vcxproj" -- FAILED.
```
Does libgit2 build not included to solution ?

**Comment by leg0** [comment]
I didn't add reference to libgit2 project to the solution because it would be generated with cmake. If you build libgit2 first, the plugin should compile. Build libgit2 x64 by running 
```bat
cd ext\libgit2
mkdir build 
cd build 
cmake .. 
cmake --build . --config Debug
```
 (or Release) in the libgit2 root directory, the plugin should compile. To build x86 version of libgit you would instead do run 
```bat
cd ext\libgit2
mkdir build
cd build
cmake -A Win32 .. 
cmake --build . --config Debug
```
I'm not sure how to properly integrate this without using cmake to generate the project and the solution in the first place. Maybe pre-build event or just a bat file that should be run before the first build.

**Comment by smithx** [comment]
I've built it finally. But Far crash when I try to go to submodule directory (.  Is it reproduced for you ?

**Comment by leg0** [comment]
Yes, I can reproduce it. I'll figure out why that happens. Once I have fix, I'll update the PR.

**Comment by smithx** [comment]
Would you make name for detached branches as first digits of hash, like '(957d76e...)', now is faceless 'HEAD'

**Pull request merged**
